### ISSUE TITLE
Quests barely visible

### ISSUE THREAD

**Issue by scarletgreed** [rgtexa/Automaton#13]
When I opened the quest book it looked like this:
![2018-05-30_18 42 58](https://user-images.githubusercontent.com/35054133/40734992-4eef9814-643a-11e8-89a4-f22b3fbcb6b2.png)
After trying A LOT of things, I discovered that the quests were right there. But I have to put the zoom at 50% and go all to the left, to see this:
![2018-05-30_18 51 58](https://user-images.githubusercontent.com/35054133/40735099-902e492e-643a-11e8-88a1-5c525c376b0a.png)
Now the problem is that every time I open the quest book the zoom is again at 100% and centred, so I have to reduce de zoom and move to the left constantly. 

Is this working as intended? There is any way to change it? 

I have no other mods added to the pack and I've already tried to reset the quests.

**EDIT**: I have resolved this for myself editing the database to move all the quest to the right. I don't think is an optimal solution but I'll leave the edited DefaultQuests here, it may help someone:
[https://www.dropbox.com/s/8y3qa6kpmrz4v9x/DefaultQuests.json?dl=0](url)

**Comment by Peter-Pwn** [comment]
Are you playing version 1.1.0 of the pack? It looks like the used version of BetterQuesting had a bug with the alignment. Someone reported the same issue here https://github.com/rgtexa/Automaton/issues/9#issuecomment-383749792. It  seems that updating the mod solved the problem.

I'am playing version 1.2.0 and have no problems with BetterQuesting.

**Comment by rgtexa** [comment]
Fixed in 1.3.0.
