### ISSUE TITLE
Can't insert diesel from immersive petroleum into diesel generator

### ISSUE THREAD

**Issue by mactyre** [rgtexa/Automaton#15]
I can't input diesel that I generate from my distillation tower, into the diesel generator, I even tried to use different types of tanks and pipes still, It just sits there in the tank or the pipe without moving

**Comment by MichelArendt** [comment]
I've also had some issues with that. Had to go into creative to find out how it worked (mainly cuz pums work weirdly). That's how your setup should be (remember your need a pump to extract from the tank):

![screenshot_1](https://user-images.githubusercontent.com/5015666/42063942-8d6d8b3c-7b0a-11e8-81c5-af5355bddfca.png)
![screenshot_2](https://user-images.githubusercontent.com/5015666/42063943-8d95aa04-7b0a-11e8-82a2-26a7d5a773af.png)

**Comment by mactyre** [comment]
I think you are talking about bio-diesel? because the setup that's in the picture has garden cloches, and a refinery
I'm actually talking about diesel that you can get from the distillation tower

**Comment by rgtexa** [comment]
I just tested and the Diesel Generator runs on Diesel successfully.

Do note that the Distillation Tower outputs from the bottom-up when viewing the liquids in the interface. The first fluid output will be Gasoline, so if you are trying to pump directly from the Distillation Tower into the Diesel Generator, it will not work - you'll need intermediate tanks to store the Gasoline and Lubricant at minimum.

Also, depending on what tanks you are using, they may require extra infrastructure. The IE tanks require a redstone signal applied to the tank to enable output, and a powered liquid pump if using the IE pipes as well.

**Comment by mactyre** [comment]
Well on my case I was pretty sure that I'm pumping diesel and not anything else because I have a fluid router on the output of the tower and then three tanks for the three different fluids.
I even tried to grab a bucket of diesel from creative gamemode and I emptied the bucket inside a mekanism tank and an ender storage tank and still nothing happened

P.S I'm running version 1.1.0 of the modpack and I've updated two mods ( MCMultipart and woot because there was a bug with headhunter enchantment and it was fixed in later versions )
