### ISSUE TITLE
[Automaton 1.1.0 / MC 1.12.2] Beacon powers don't apply properly

### ISSUE THREAD

**Issue by MichelArendt** [rgtexa/Automaton#16]
I've set up a full beacon (6 beacons) on top of my base and found out that there's an issue with the mod-pack when applying buffs. I've set up a few screenshots to demonstrate the issue.

### Vanilla First one, is a screenshot of a Vanilla-created full beacon:
[Vanilla Beacon with buffs](https://ibb.co/jPwH4o)

As you can see, everything works as expected and the beacon applies the buffs on all directions.

### Automaton 1.1.0
[Automaton 1.1.0 Beacon](https://ibb.co/ezFoAT)

On Automaton 1.1.0, the beacon, apparently, does not gives any buffs as demonstrated on the screenshot. I've even tried recreating the same beacon on creative (same results).

However, the beacon does applies the buffs. Although not correctly:
[Automaton 1.10 Beacon with buffs](https://ibb.co/bzcqPo)

The buffs only apply on the Y+ position of the beacon, and to the south-east portion of the range, not the other sides.

I though this could be a Lava armor-set issue, but removing it didn't work.

### Conclusion
I'm led to the conclusion that this is an issue with this mod-pack. However, I've added a few utility mods to the setup so, I'll leave my mod-list below to help you in debugging this issue:

- BetterFps-1.4.8
- InventoryTweaks-1.63
- jei_1.12.2-4.10.0.198
- journeymap-1.12.2-5.5.2
- LLOverlayReloaded-1.1.6-mc1.12.2
- OptiFine_1.12.2_HD_U_D3

Those are all of the mods included, along with Automaton.

**Comment by rgtexa** [comment]
This should be fixed in 1.5.0 - there is a config in BetterFPS that is experimental and appears to cause this behavior that has been changed in the 1.5.0 version of the pack.
