### ISSUE TITLE
AE2 & AE2 Stuff not accepting presses

### ISSUE THREAD

**Issue by Spanky1044sback** [rgtexa/Automaton#17]
Hello,

I was really enjoying the mod pack, however, now the AE2 Stuff Advanced Inscriber will not accept anything, and the standard AE2 Inscriber will only accept items placed in the middle slot. I even just tried updating to the latest stable version (11) of AE2 with no luck.

Any help would be appreciated.

Thank you

**Comment by rgtexa** [comment]
What version of the pack are you using? Have you added any mods to the pack?

I've just tested the inscribers in 1.1.0, 1.2.0, and the 1.3.0 version released today and have not been able to replicate.

**Comment by Spanky1044sback** [comment]
I only added the client side only mods for visuals until the problem occurred. I.E. Betterfoliage, Dsound, and most of the others included in the list found within the forum/comments section. After the event happened, that is when I installed Refined Storage to replace AE2. Makes it a pain to due the AE2 quests, but if you call most everything "even" it's almost a fair trade to swap stuff creatively just to complete the quests.

As for the version, I just downloaded the pack version 1.2.0 a couple days prior to the incident occurring and inscribers were working fine in the beginning. However, a save and restart of the pack later, no presses were excepted in the AE2 Stuff Advanced Inscriber and the AE2 Inscriber only accepted the presses in the slot where you would put your Redstone, Silicon, Gold... not in any of the locking slots where the press needs to go. And I did try both locking and unlocking the slots to make sure that was not the issue.

**Comment by Blapor** [comment]
I've also run into this problem with the Advanced Inscriber (not the regular Inscriber, that works just fine). I can put in ingredients and such, but it just doesn't make anything. I have it all hooked up correctly, so it seems like this is still a bug. I have added no extra mods to the pack, and I'm on the most current version.
