### ISSUE TITLE
Algorithm causing weird stuff

### ISSUE THREAD

**Issue by StalkerM8** [rgtexa/Automaton#20]
* Minecraft Version: 1.12.2
* BetterFps Version: Unknown
* Forge/LiteLoader Version (if any): 8.0.99.99 forge mod loader
* Crash Logs (if any): none
* Other Mods (if any): within the modpack "Automation" version 1.4.0 according to Twitch
---
When set to Taylors algorithm i get upwards of 120 fps which is great however the arms of my player model spaz out and trying to walk ends up doing the same causing everything to spazz out like a ragdoll first person view, while also causing everything to unrender and re-render in once a few seconds have past, any other algorithm is fine but yeilds less than 40 or 50 fps

**Comment by rgtexa** [comment]
This would be better reported to the BetterFPS devs. I cannot reproduce this issue.
