### ISSUE TITLE
Mining drill head not equipping

### ISSUE THREAD

**Issue by Cnights** [rgtexa/Automaton#4]
I made the mining drill and both an iron and steel head. I can put them together in the workbench but the drill shows no head equipped.

**Comment by rgtexa** [comment]
This was reported by myself on the [Immersive Engineering Github](https://github.com/BluSunrize/ImmersiveEngineering/issues/2726) and was closed with a fix for the next release of Immersive Engineering.

I'm holding the next release of Automaton (1.1.0) waiting for this release so I can include it in the pack.

**Comment by Cnights** [comment]
Sounds good. Any idea how soon that might be? Thanks.

**Comment by rgtexa** [comment]
Wish I could say, but I don't know when their next release is planned, and in looking at the release history, it doesn't look like they have a set schedule.

**Comment by rgtexa** [comment]
Fixed in 1.2.0 release with Immersive Engineering 0.78.
