### ISSUE TITLE
IE connectors not transferring power to AE

### ISSUE THREAD

**Issue by Cnights** [rgtexa/Automaton#5]
I’m trying to use MV connectors and wires to power my ME system. When I set it up through the power acceptor it will give my controller a full charge then stop till I tear the whole system down and rebuild it. Relogging doesn’t help either. I’m guessing this is an IE issue?

**Comment by rgtexa** [comment]
There is a note on this in the energy acceptor quest - you can still use your IE power for the ME system by using another power cable in between - for example, if you place a Mekanism Universal Cable on the Energy Acceptor and then connect your IE connector to that cable, it will work fine.

This is an issue with how IE decided to implement their energy system for 1.10+ before the RF API was available and with the Forge Energy capability - it creates some incompatibilities with other mods. And unfortunately, they're not going to change it, so we have to get creative to work around its quirks.

[See IE issue #1622](https://github.com/BluSunrize/ImmersiveEngineering/issues/1622)
