### ISSUE TITLE
Recipes missing

### ISSUE THREAD

**Issue by cogscreamsrage** [rgtexa/Automaton#6]
After updating to the new version of the modpack, alot of recipes are missing or not showing in JEI, mekanism machines, and Immersive Engineering items, and some AE 2 items.

**Comment by rgtexa** [comment]
You may want to reinstall the pack - in a fresh install I'm not seeing any missing recipes.

The pack doesn't change any IE recipes at all, and only changes a total of 15 recipes across the entire pack. The only AE2 recipes modified are the controller and the wireless receiver and terminal. The only Mekanism recipes altered are the steel casing, metallurgic infuser, induction matrix casing, reactor controller and casing, and the atomic disassembler.
